import DOMPurify from 'dompurify';

const sanitizeHtml = (html) => {
  if (!html) return '';
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      'p',
      'br',
      'b',
      'i',
      'u',
      'em',
      'strong',
      'a',
      'ul',
      'ol',
      'li',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'img',
      'span',
      'div',
      'sub',
      'sup',
      'table',
      'thead',
      'tbody',
      'tr',
      'th',
      'td',
      'blockquote',
      'pre',
      'code',
      'hr',
      'figure',
      'figcaption',
      'video',
      'source',
    ],
    ALLOWED_ATTR: [
      'href',
      'target',
      'src',
      'alt',
      'width',
      'height',
      'class',
      'style',
      'id',
      'rel',
      'type',
      'controls',
      'autoplay',
      'loop',
      'muted',
      'poster',
    ],
    ADD_ATTR: ['target'],
  });
};

export default sanitizeHtml;
